const pokemons = [
  {
    name: "amogus",
    type: ["sus", "amogus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 1,
  },
  {
    name: "amogus",
    type: ["sussy"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 2,
  },
  {
    name: "amogus",
    type: ["sussy"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 3,
  },
  {
    name: "amogus",
    type: ["sussy"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 4,
  },
  {
    name: "amogus",
    type: ["sus", "impostor"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 5,
  },
  {
    name: "amogus",
    type: ["amogus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 6,
  },
  {
    name: "amogus",
    type: ["amogus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 7,
  },
  {
    name: "amogus",
    type: ["impostor"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 8,
  },
  {
    name: "amogus",
    type: ["sussy", "impostor"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 9,
  },
  {
    name: "amogus",
    type: ["amogus", "impostor"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 10,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 11,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 12,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 13,
  },
  {
    name: "amogus",
    type: ["sussy"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 14,
  },
  {
    name: "amogus",
    type: ["sussy"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 15,
  },
  {
    name: "damogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 16,
  },
  {
    name: "gamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 17,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 18,
  },
  {
    name: "bamogus",
    type: ["amogus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 19,
  },
  {
    name: "bamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 20,
  },
  {
    name: "amogus",
    type: ["impostor"],
    height: 69,
    weight: 69,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 21,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 22,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 23,
  },
  {
    name: "qamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 24,
  },
  {
    name: "Qamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 25,
  },
  {
    name: "samogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 26,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 27,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 28,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 25,
    weight: 999,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 29,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 30,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 1,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 31,
  },
  {
    name: "lamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 32,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 33,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 34,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 35,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 36,
  },
  {
    name: "zamogus",
    type: ["sus"],
    height: 123,
    weight: 456,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 37,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 38,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 39,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 40,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 999,
    weight: 12,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 41,
  },
  {
    name: "xamogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 42,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 43,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 44,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 45,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 20,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 46,
  },
  {
    name: "yamogus",
    type: ["sus"],
    height: 42,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 47,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 48,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 49,
  },
  {
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
    id: 50,
  },
];

export default pokemons;
