const pokemons = [
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 20,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus"],
    height: 10,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "amogus",
    type: ["sus", "impostor"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 69,
    name: "sussy",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
  {
    id: 60,
    name: "amogus",
    type: ["sus"],
    height: 420,
    weight: 123,
    frontViewImageUrl: "/redAmogusFront.png",
    backViewImageUrl: "/redAmogusBack.png",
    frontShinyViewImageUrl: "yellowAmogusFront.png",
    backShinyViewImageUrl: "yellowAmogusBack.png",
  },
];

export default pokemons;
